version: '3.1'

services:

  webserver:
    build: 
      context: ./webserver
    container_name: ${PROJECT_NAME}-webserver
    restart: always
    links:
      - database
    ports:
      - ${HOST_MACHINE_UNSECURE_APACHE_PORT}:80
      - ${HOST_MACHINE_SECURE_APACHE_PORT}:443
    volumes:
      - ./app:/var/www/html
      - ./webserver/logs:/var/log/apache2
      - ./webserver/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./webserver/sites:/etc/apache2/sites-enabled
      - ./webserver/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./webserver/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key

  database:
    image: mysql:8
    command: mysqld --log-error=/var/log/mysql/error.log --general-log=1 --general-log-file=/var/log/mysql/general.log --default-authentication-plugin=mysql_native_password
    container_name: ${PROJECT_NAME}-database
    restart: always
    ports:
      - ${HOST_MACHINE_MYSQL_PORT}:3306
    volumes:
      - ./database/entrypoint:/docker-entrypoint-initdb.d
      - ./database/logs:/var/log/mysql
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: always
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - ${HOST_MACHINE_PMA_PORT}:80

